version: '3.8'
services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codepushdb
      MYSQL_USER: codepush
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"

  app:
    build:
      context: .  # This tells Docker to look for the Dockerfile in the current 'api/' directory
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_NAME: codepushdb
      DB_USER: codepush
      DB_PASS: root
    volumes:
      - .:/code-push-server/api
    command: >
      sh -c "npm install && npm run start:env && node seedData.js"

volumes:
  db_data:
